version: "1.0"
services:
  db:
    image: 'mongo:latest'
    environment:
      - MONGO_INITDB_ROOT_USERNAME=mongoadmin
      - MONGO_INITDB_ROOT_PASSWORD=password
    volumes:
      - mongo-data:/data/db
    expose:
      - 27017
    ports:
      - "27017:27017"
    restart: on-failure
    healthcheck:
      test:
        [
          "CMD",
          "mongosh",
          "--quiet",
          "127.0.0.1/admin",
          "--eval",
          "'quit(db.runCommand({ ping: 1 }).ok ? 0 : 2)'"
        ]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 10s

  account-app:
    build: ./accountapi/.
    ports:
      - "8080:8080"
    links:
      - db
    depends_on:
      db:
        condition: service_healthy
  
  player-app:
    build: ./player/.
    ports:
      - "8081:8080"
    links:
      - db
      - account-app
    depends_on:
      db:
          condition: service_healthy

volumes:
  mongo-data: