services:
  db:
    image: 'mongo:latest'
    ports:
      - '27017:27017'
    restart: always

  app-server:
    build: .
    depends_on:
      - db
    ports:
      - '8081:8080'
    restart: always