services:
  db:
    image: 'mongo:latest'
    ports:
      - '27017:27017'
    restart: always

  app-server:
    image: 'gachi-player/spring:latest'
    depends_on:
      - db
    ports:
      - '8081:8081'
    restart: always