services:
  db:
    image: 'mongo:latest'
    environment:
      - MONGO_INITDB_ROOT_USERNAME=mongoadmin
      - MONGO_INITDB_ROOT_PASSWORD=password
    expose:
      - 27017
    ports:
      - '27017:27017'
    restart: always

  app-server:
    build: .
    depends_on:
      - db
    ports:
      - '8081:8080'
    restart: always