services:
  db:
    image: 'mongo:latest'
    ports:
      - '27017:27017'
    restart: always

  app-server:
    image: 'gachi-api/spring:latest'
    depends_on:
      - db
    ports:
      - '8080:8080'
    restart: always