version: '3.3'
services:
  monster-mongo:
    image: mongo
    ports:
      - '27017:27017'
    container_name: monster-mongo
    restart: always
    environment:
      - MONGO_INITDB_ROOT_USERNAME=mongoadmin
      - MONGO_INITDB_ROOT_PASSWORD=password
    volumes:
      - ./mongodb_data_container:/data/db

  monster-app:
    build: .
    image: monster-app
    container_name: monster-app
    ports:
      - "8085:8080"
    links:
      - monster-mongo
    depends_on:
      - monster-mongo
