version: '3.3'
services:
  mongo:
    ports:
      - '27017:27017'
    container_name: mongoMonster
    restart: always
    environment:
      - MONGO_INITDB_ROOT_USERNAME=mongoadmin
      - MONGO_INITDB_ROOT_PASSWORD=password
    image: mongo